# Generated by Django 3.0.4 on 2020-03-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(max_length=256)),
                ('nickname', models.CharField(max_length=256)),
                ('who', models.TextField()),
                ('why', models.TextField()),
                ('what', models.TextField()),
            ],
        ),
    ]
