# Generated by Django 3.0.4 on 2020-03-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('duration', models.DurationField()),
                ('current_heartbeats', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='what',
            new_name='about',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='who',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='why',
        ),
    ]
