# Generated by Django 3.0.4 on 2020-03-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200313_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_heartbeats', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='promise',
            name='current_heartbeats',
        ),
        migrations.AddField(
            model_name='promise',
            name='target_heartbeats',
            field=models.IntegerField(default=1000000),
        ),
    ]
