# Generated by Django 3.0.4 on 2020-03-27 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200327_0540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'verbose_name_plural': 'Progressions'},
        ),
    ]
