# Generated by Django 3.0.4 on 2020-04-15 06:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200327_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='realname',
        ),
        migrations.RemoveField(
            model_name='promise',
            name='start_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='firstname',
            field=models.CharField(default='Wil', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.CharField(default='Wil', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progress',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promise',
            name='charity_name',
            field=models.CharField(default='Good+', max_length=256),
            preserve_default=False,
        ),
    ]
